In [1]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.6.17)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://books.toscrape.com"

response = requests.get(url)

print(response.status_code)

200

In [4]:
soup = BeautifulSoup(response.text, "html.parser")

In [5]:
url = "https://books.toscrape.com"

response = requests.get(url)

print(response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

200

In [6]:
books = soup.find_all("article", class_="product_pod")

print("Number of books on this page:", len(books))

Number of books on this page: 20

In [7]:
titles = []
prices = []
ratings = []
availability = []

In [8]:
for book in books:

    # Book Title
    title = book.h3.a["title"]

    # Price
    price = book.find("p", class_="price_color").text

    # Rating
    rating = book.p["class"][1]

    # Availability
    stock = book.find("p", class_="instock availability").text.strip()

    # Store data in lists
    titles.append(title)
    prices.append(price)
    ratings.append(rating)
    availability.append(stock)

In [9]:
print("Titles:", len(titles))
print("Prices:", len(prices))
print("Ratings:", len(ratings))
print("Availability:", len(availability))

Titles: 20
Prices: 20
Ratings: 20
Availability: 20

In [10]:
df = pd.DataFrame({
    "Title": titles,
    "Price": prices,
    "Rating": ratings,
    "Availability": availability
})

df.head()

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [11]:
titles = []
prices = []
ratings = []
availability = []

In [12]:
import requests
from bs4 import BeautifulSoup

# Empty lists
titles = []
prices = []
ratings = []
availability = []
categories = []
product_urls = []

base_url = "https://books.toscrape.com/catalogue/page-{}.html"

for page in range(1, 51):

    url = base_url.format(page)
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:

        title = book.h3.a["title"]
        price = book.find("p", class_="price_color").text
        rating = book.p["class"][1]
        stock = book.find("p", class_="instock availability").text.strip()

        # Product URL
        product_url = "https://books.toscrape.com/catalogue/" + book.h3.a["href"].replace("../", "")

        # Open product page
        product_response = requests.get(product_url)
        product_soup = BeautifulSoup(product_response.text, "html.parser")

        # Category
        category = product_soup.find("ul", class_="breadcrumb").find_all("li")[2].text.strip()

        # Save data
        titles.append(title)
        prices.append(price)
        ratings.append(rating)
        availability.append(stock)
        categories.append(category)
        product_urls.append(product_url)

print("Total Books:", len(titles))

Total Books: 1000

In [13]:
df = pd.DataFrame({
    "Title": titles,
    "Price": prices,
    "Rating": ratings,
    "Availability": availability
})

df.head()

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [14]:
df = pd.DataFrame({
    "Title": titles,
    "Price": prices,
    "Rating": ratings,
    "Availability": availability,
    "Category": categories,
    "Product_URL": product_urls
})

df.head()

,Title,Price,Rating,Availability,Category,Product_URL
0,A Light in the Attic,Â£51.77,Three,In stock,Poetry,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,Â£53.74,One,In stock,Historical Fiction,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,Â£50.10,One,In stock,Fiction,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,Â£47.82,Four,In stock,Mystery,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,History,https://books.toscrape.com/catalogue/sapiens-a...

In [15]:
df.to_csv("books_data.csv", index=False)

In [16]:
df.to_csv("books_data.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         1000 non-null   object
 1   Price         1000 non-null   object
 2   Rating        1000 non-null   object
 3   Availability  1000 non-null   object
 4   Category      1000 non-null   object
 5   Product_URL   1000 non-null   object
dtypes: object(6)
memory usage: 47.0+ KB

In [18]:
df.describe(include="all")

,Title,Price,Rating,Availability,Category,Product_URL
count,1000,1000,1000,1000,1000,1000
unique,999,903,5,1,50,1000
top,The Star-Touched Queen,Â£44.18,One,In stock,Default,https://books.toscrape.com/catalogue/1000-plac...
freq,2,3,226,1000,152,1

In [19]:
df.to_csv("books_data.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

In [20]:
from google.colab import files

files.download("books_data.csv")